name: Website Scanner
permissions: write-all

on:
  push:
      branches:
        -master
     
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2   
        
      - name: Run Dastardly Action Step
        continue-on-error: true                        # This allows subsequent steps to run even if this step fails
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://123movies.com.pk/watch-barbie-2023-online-free-hd1234567890123/'

  # You can replace this next step with any JUnit XML parser of your choosing
      - name: Publish Test Report
        if: always()                                    # Forces this step to always run
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'       # You need to update this path if you pass in a different output filename to the Dastardly action
          require_tests: true
          
      - name: Upload Test Report
        if: always ()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/dastardly-report.xml'
          
